[server]
  host: 0.0.0.0
  port: 7125
  klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

  [file_manager]
  config_path: /home/pi/printer_data/config
  log_path: /home/pi/printer_data/logs

  [authorization]
  trusted_clients:
      127.0.0.1
      192.168.0.0/16
      10.0.0.0/8
      172.16.0.0/12
  cors_domains:
      *.local
      *.lan
      *://localhost
      *://localhost:*
      *://127.0.0.1
      *://127.0.0.1:*
      http://mini-klipper.local
      http://mini-klipper.local:*
